/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas_universidad;

/**
 *
 * @author Administrador
 */
public class VistaUniversidad extends javax.swing.JFrame {

    /**
     * Creates new form jAlumno
     */
    public VistaUniversidad() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar2 = new javax.swing.JMenuBar();
        jmArchivo = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jmMaterias = new javax.swing.JMenu();
        jmMat = new javax.swing.JMenuItem();
        jmAlumno = new javax.swing.JMenu();
        jmAlum = new javax.swing.JMenuItem();
        jmInscripcion = new javax.swing.JMenu();
        jmInsc = new javax.swing.JMenuItem();
        jmCargaNotas = new javax.swing.JMenu();
        jmMan = new javax.swing.JMenuItem();
        jmConsultas = new javax.swing.JMenu();
        jmListAlum = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 488, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 345, Short.MAX_VALUE)
        );

        jmArchivo.setText("Archivo");

        jMenuItem1.setText("Salir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jmArchivo.add(jMenuItem1);

        jMenuBar2.add(jmArchivo);

        jmMaterias.setText("Materias");

        jmMat.setText("Formulario de Materias");
        jmMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmMatActionPerformed(evt);
            }
        });
        jmMaterias.add(jmMat);

        jMenuBar2.add(jmMaterias);

        jmAlumno.setText("Alumnos");
        jmAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmAlumnoActionPerformed(evt);
            }
        });

        jmAlum.setText("Formulario de Alumnos");
        jmAlum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmAlumActionPerformed(evt);
            }
        });
        jmAlumno.add(jmAlum);

        jMenuBar2.add(jmAlumno);

        jmInscripcion.setText("Inscripciones");

        jmInsc.setText("Manejo de Inscripciones");
        jmInsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmInscActionPerformed(evt);
            }
        });
        jmInscripcion.add(jmInsc);

        jMenuBar2.add(jmInscripcion);

        jmCargaNotas.setText("Carga de Notas");
        jmCargaNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCargaNotasActionPerformed(evt);
            }
        });

        jmMan.setText("Manipulación de Notas");
        jmMan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmManActionPerformed(evt);
            }
        });
        jmCargaNotas.add(jmMan);

        jMenuBar2.add(jmCargaNotas);

        jmConsultas.setText("Consultas");

        jmListAlum.setText("Listado de Alumnos x Materia");
        jmListAlum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmListAlumActionPerformed(evt);
            }
        });
        jmConsultas.add(jmListAlum);

        jMenuBar2.add(jmConsultas);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jmInscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmInscActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmInscActionPerformed

    private void jmAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmAlumnoActionPerformed
        // TODO add your handling code here:
         
    }//GEN-LAST:event_jmAlumnoActionPerformed

    private void jmAlumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmAlumActionPerformed
        // TODO add your handling code here:
          escritorio.removeAll();
          escritorio.repaint();
          VistaAlumnos va=new VistaAlumnos();
          va.setVisible(true);
          escritorio.add(va);
          escritorio.moveToFront(va);
    }//GEN-LAST:event_jmAlumActionPerformed

    private void jmMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmMatActionPerformed
        // TODO add your handling code here:
          escritorio.removeAll();
          escritorio.repaint();
          VistaMaterias vm = new VistaMaterias();
          vm.setVisible(true);
          escritorio.add(vm);
          escritorio.moveToFront(vm);
    }//GEN-LAST:event_jmMatActionPerformed

    private void jmListAlumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmListAlumActionPerformed
        // TODO add your handling code here:
          escritorio.removeAll();
          escritorio.repaint();
          VistaAlumnosMaterias vam = new VistaAlumnosMaterias();
          vam.setVisible(true);
          escritorio.add(vam);
          escritorio.moveToFront(vam);
    }//GEN-LAST:event_jmListAlumActionPerformed

    private void jmCargaNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCargaNotasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmCargaNotasActionPerformed

    private void jmManActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmManActionPerformed
        // TODO add your handling code here:
          escritorio.removeAll();
          escritorio.repaint();
          VistaCargarNota vcn = new VistaCargarNota();
          vcn.setVisible(true);
          escritorio.add(vcn);
          escritorio.moveToFront(vcn);
    }//GEN-LAST:event_jmManActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaUniversidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaUniversidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaUniversidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaUniversidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaUniversidad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jmAlum;
    private javax.swing.JMenu jmAlumno;
    private javax.swing.JMenu jmArchivo;
    private javax.swing.JMenu jmCargaNotas;
    private javax.swing.JMenu jmConsultas;
    private javax.swing.JMenuItem jmInsc;
    private javax.swing.JMenu jmInscripcion;
    private javax.swing.JMenuItem jmListAlum;
    private javax.swing.JMenuItem jmMan;
    private javax.swing.JMenuItem jmMat;
    private javax.swing.JMenu jmMaterias;
    // End of variables declaration//GEN-END:variables
}
